In [1]:
!wget https://raw.githubusercontent.com/malin84/transportation_networks_of_china/refs/heads/main/pref_pair/time_cost_prefecture_pair_road.csv

--2024-12-07 20:33:57--  https://raw.githubusercontent.com/malin84/transportation_networks_of_china/refs/heads/main/pref_pair/time_cost_prefecture_pair_road.csv
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ...
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：6903277 (6.6M) [text/plain]
正在保存至: “time_cost_prefecture_pair_road.csv”

time_cost_prefectur 100%[===================>]   6.58M  20.5MB/s  用时 0.3s

2024-12-07 20:33:58 (20.5 MB/s) - 已保存 “time_cost_prefecture_pair_road.csv” [6903277/6903277])

In [2]:
!wget https://raw.githubusercontent.com/malin84/transportation_networks_of_china/refs/heads/main/pref_pair/cityinfo.csv

--2024-12-07 20:37:10--  https://raw.githubusercontent.com/malin84/transportation_networks_of_china/refs/heads/main/pref_pair/cityinfo.csv
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ...
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：25676 (25K) [text/plain]
正在保存至: “cityinfo.csv”

cityinfo.csv        100%[===================>]  25.07K  --.-KB/s  用时 0.001s

2024-12-07 20:37:10 (27.8 MB/s) - 已保存 “cityinfo.csv” [25676/25676])

In [3]:
import numpy as np
import pandas as pd

In [42]:
df = pd.read_csv('time_cost_prefecture_pair_road.csv')

In [43]:
df_test = df.pivot(index='origin', columns='destination', values= 'year_2017')

In [44]:
df_test[1101] = [np.nan] * len(df_test)

In [54]:
df_test = df_test.sort_index(axis = 1)

In [51]:
df_test.loc[6502] = [np.nan] * (len(df_test)+1)

In [55]:
df_test

destination,1101,1201,1301,1302,1303,1304,1305,1306,1307,1308,...,6211,6212,6301,6401,6402,6403,6404,6405,6501,6502
origin,,,,,,,,,,,,,,,,,,,,,
1101,NaN,1.423,3.274,2.118,3.148,4.597,4.226,2.271,2.619,2.306,...,14.553,17.093,16.323,10.903,11.163,10.933,13.656,12.446,30.097,32.881
1201,NaN,NaN,3.255,1.314,2.638,4.577,4.206,2.251,3.894,3.007,...,14.618,17.158,16.463,11.043,11.438,11.074,13.738,12.586,30.237,33.021
1301,NaN,NaN,NaN,4.394,5.718,2.395,2.024,2.299,5.170,5.389,...,12.376,14.916,14.336,8.916,10.563,8.947,11.496,10.459,28.110,30.894
1302,NaN,NaN,NaN,NaN,1.697,5.560,5.346,3.390,4.408,2.249,...,15.757,18.297,17.602,12.182,12.578,12.213,14.877,13.725,31.376,34.160
1303,NaN,NaN,NaN,NaN,NaN,6.884,6.670,4.714,5.438,3.244,...,17.081,19.621,18.926,13.506,13.902,13.537,16.201,15.049,32.700,35.485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.410,2.165,19.816,22.600
6404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.796,21.447,24.231
6405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.174,21.958
6501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.588
6502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
for i in range(len(df_test)):
    df_test.iloc[i,i]=0

In [71]:
df_cleaned = df_test.combine_first(df_test.T)

In [72]:
df_cleaned

,1101,1201,1301,1302,1303,1304,1305,1306,1307,1308,...,6211,6212,6301,6401,6402,6403,6404,6405,6501,6502
origin,,,,,,,,,,,,,,,,,,,,,
1101,0.000,1.423,3.274,2.118,3.148,4.597,4.226,2.271,2.619,2.306,...,14.553,17.093,16.323,10.903,11.163,10.933,13.656,12.446,30.097,32.881
1201,1.423,0.000,3.255,1.314,2.638,4.577,4.206,2.251,3.894,3.007,...,14.618,17.158,16.463,11.043,11.438,11.074,13.738,12.586,30.237,33.021
1301,3.274,3.255,0.000,4.394,5.718,2.395,2.024,2.299,5.170,5.389,...,12.376,14.916,14.336,8.916,10.563,8.947,11.496,10.459,28.110,30.894
1302,2.118,1.314,4.394,0.000,1.697,5.560,5.346,3.390,4.408,2.249,...,15.757,18.297,17.602,12.182,12.578,12.213,14.877,13.725,31.376,34.160
1303,3.148,2.638,5.718,1.697,0.000,6.884,6.670,4.714,5.438,3.244,...,17.081,19.621,18.926,13.506,13.902,13.537,16.201,15.049,32.700,35.485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,10.933,11.074,8.947,12.213,13.537,9.136,8.611,9.906,9.943,13.049,...,4.765,9.095,6.074,0.776,2.422,0.000,3.410,2.165,19.816,22.600
6404,13.656,13.738,11.496,14.877,16.201,10.562,11.027,12.629,13.111,15.771,...,3.443,7.362,6.673,4.074,5.678,3.410,0.000,3.796,21.447,24.231
6405,12.446,12.586,10.459,13.725,15.049,10.648,10.123,11.418,11.750,14.561,...,5.191,9.482,6.500,2.621,4.225,2.165,3.796,0.000,19.174,21.958
6501,30.097,30.237,28.110,31.376,32.700,28.299,27.774,29.069,29.401,32.212,...,19.534,24.052,19.207,20.272,21.876,19.816,21.447,19.174,0.000,3.588
6502,32.881,33.021,30.894,34.160,35.485,31.083,30.558,31.853,32.185,34.996,...,22.318,26.836,21.992,23.056,24.660,22.600,24.231,21.958,3.588,0.000

In [74]:
mapping_df = pd.read_csv('cityinfo.csv')
mapping_df

,id,dzcode,coord_long,coord_lat,pos_x,pos_y,cityname_chn,cityname_eng,cpop2000,cpop2010,upop2000,upop2010,cityclass
0,1,1101,116.420000,39.930000,8017,3692,北京市,Beijing,1356.918900,1961.20000,1052.246000,1685.869000,7
1,2,1201,117.200000,39.119999,8159,3862,天津市,Tianjin,984.873110,1293.81990,708.981200,1027.788900,7
2,3,1301,114.520000,38.049999,7722,4125,石家庄市,Shijiazhuang,924.118590,1016.38000,323.885890,514.513310,6
3,4,1302,118.180000,39.590000,8314,3746,唐山市,Tangshan,704.055420,757.72998,226.560500,385.097500,5
4,5,1303,119.600000,39.930000,8542,3650,秦皇岛市,Qinhuangdao,275.396210,298.76001,90.013199,141.948700,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,275,6403,106.230000,37.980000,6314,4145,吴忠市,Wuzhong,190.604100,127.37920,56.319901,48.032001,2
275,276,6404,106.260000,36.049999,6303,4572,固原市,Guyuan,172.736100,122.81560,15.572700,27.946199,2
276,277,6405,105.230000,37.520000,6140,4240,中卫市,Zhongwei,152.015500,108.08320,17.766939,31.883900,2
277,278,6501,87.620003,43.820000,3475,2479,乌鲁木齐市,Urumqi,208.183400,311.02802,173.887600,286.539490,4
278,279,6502,84.870003,45.599998,3154,2001,克拉玛依市,Karamay,27.023199,39.10080,27.023199,35.329899,2

In [78]:
mapping = dict(zip(mapping_df['dzcode'],mapping_df['cityname_eng']))

In [79]:
mapping

{1101: 'Beijing',
 1201: 'Tianjin',
 1301: 'Shijiazhuang',
 1302: 'Tangshan',
 1303: 'Qinhuangdao',
 1304: 'Handan',
 1305: 'Xingtai',
 1306: 'Baoding',
 1307: 'Zhangjiakou',
 1308: 'Chengde',
 1309: 'Cangzhou',
 1310: 'Langfang',
 1311: 'Hengshui',
 1401: 'Taiyuan',
 1402: 'Datong',
 1403: 'Yangquan',
 1404: 'Changzhi',
 1405: 'Jincheng',
 1406: 'Shuozhou',
 1407: 'Jinzhong',
 1408: 'Yuncheng',
 1409: 'Xinzhou',
 1410: 'Linfen',
 1411: 'Luliang',
 1501: 'Hohhot',
 1502: 'Baotou',
 1503: 'Wuhai',
 1504: 'Chifeng',
 1505: 'Tongliao',
 1506: 'Erdos',
 1507: 'Hulunbeir',
 1508: 'Bayannaoer',
 1509: 'Ulanchabu',
 2101: 'Shenyang',
 2102: 'Dalian',
 2103: 'Anshan',
 2104: 'Fushun',
 2105: 'Benxi',
 2106: 'Dandong',
 2107: 'Jinzhou',
 2108: 'Yingkou',
 2109: 'Fuxin',
 2110: 'Liaoyang',
 2111: 'Panjin',
 2112: 'Tieling',
 2113: 'Chaoyang',
 2114: 'Huludao',
 2201: 'Changchun',
 2202: 'Jilin',
 2203: 'Siping',
 2204: 'Liaoyuan',
 2205: 'Tonghua',
 2206: 'Baishan',
 2208: 'Baicheng',
 2301: 'Harbin',
 2302: 'Qiqihar',
 2303: 'Jixi',
 2304: 'Hegang',
 2305: 'Shuangyashan',
 2306: 'Daqing',
 2307: 'Yichun1',
 2308: 'Jiamusi',
 2309: 'Qitaihe',
 2310: 'Mudanjiang',
 2311: 'Heihe',
 3101: 'Shanghai',
 3201: 'Nanjing',
 3202: 'Wuxi',
 3203: 'Xuzhou',
 3204: 'Changzhou',
 3205: 'Suzhou1',
 3206: 'Nantong',
 3207: 'Lianyungang',
 3208: 'Huaian',
 3209: 'Yancheng',
 3210: 'Yangzhou',
 3211: 'Zhenjiang',
 3212: 'Taizhou4',
 3213: 'Suqian',
 3301: 'Hangzhou',
 3302: 'Ningbo',
 3303: 'Wenzhou',
 3304: 'Jiaxing',
 3305: 'Huzhou',
 3306: 'Shaoxing',
 3307: 'Jinhua',
 3308: 'Quzhou',
 3309: 'Zhoushan',
 3310: 'Taizhou2',
 3311: 'Lishui',
 3401: 'Hefei',
 3402: 'Wuhu',
 3403: 'Bengbu',
 3404: 'Huainan',
 3405: 'Maanshan',
 3406: 'Huaibei',
 3407: 'Tongling',
 3408: 'Anqing',
 3410: 'Huangshan',
 3411: 'Chuzhou',
 3412: 'Fuyang',
 3413: 'Suzhou4',
 3415: 'Liuan',
 3416: 'Bozhou',
 3417: 'Chizhou',
 3418: 'Xuancheng',
 3501: 'Fuzhou2',
 3502: 'Xiamen',
 3503: 'Putian',
 3504: 'Sanming',
 3505: 'Quanzhou',
 3506: 'Zhangzhou',
 3507: 'Nanping',
 3508: 'Longyan',
 3509: 'Ningde',
 3601: 'Nanchang',
 3602: 'Jingdezhen',
 3603: 'Pingxiang',
 3604: 'Jiujiang',
 3605: 'Xinyu',
 3606: 'Yingtan',
 3607: 'Ganzhou',
 3608: 'JiAn',
 3609: 'Yichun2',
 3610: 'Fuzhou3',
 3611: 'Shangrao',
 3701: 'JiNan',
 3702: 'Qingdao',
 3703: 'Zibo',
 3704: 'Zaozhuang',
 3705: 'Dongying',
 3706: 'Yantai',
 3707: 'Weifang',
 3708: 'Jining',
 3709: 'Taian',
 3710: 'Weihai',
 3711: 'Rizhao',
 3712: 'Laiwu',
 3713: 'Linyi',
 3714: 'Dezhou',
 3715: 'Liaocheng',
 3716: 'Binzhou',
 3717: 'Heze',
 4101: 'Zhengzhou',
 4102: 'Kaifeng',
 4103: 'Luoyang',
 4104: 'Pingdingshan',
 4105: 'Anyang',
 4106: 'Hebi',
 4107: 'Xinxiang',
 4108: 'Jiaozuo',
 4109: 'Puyang',
 4110: 'Xuchang',
 4111: 'Luohe',
 4112: 'Sanmenxia',
 4113: 'Nanyang',
 4114: 'Shangqiu',
 4115: 'Xinyang',
 4116: 'Zhoukou',
 4117: 'Zhumadian',
 4201: 'Wuhan',
 4202: 'Huangshi',
 4203: 'Shiyan',
 4205: 'Yichang',
 4206: 'Xiangfan',
 4207: 'Ezhou',
 4208: 'Jingmen',
 4209: 'Xiaogan',
 4210: 'Jingzhou',
 4211: 'Huanggang',
 4212: 'Xianning',
 4213: 'Suizhou',
 4301: 'Changsha',
 4302: 'Zhuzhou',
 4303: 'Xiangtan',
 4304: 'Hengyang',
 4305: 'Shaoyang',
 4306: 'Yueyang',
 4307: 'Changde',
 4308: 'Zhangjiajie',
 4309: 'Yiyang',
 4310: 'Chenzhou',
 4311: 'Yongzhou',
 4312: 'Huaihua',
 4313: 'Loudi',
 4401: 'Guangzhou',
 4402: 'Shaoguan',
 4403: 'Shenzhen',
 4404: 'Zhuhai',
 4405: 'Shantou',
 4406: 'Foshan',
 4407: 'Jiangmen',
 4408: 'Zhanjiang',
 4409: 'Maoming',
 4412: 'Zhaoqing',
 4413: 'Huizhou',
 4414: 'Meizhou',
 4415: 'Shanwei',
 4416: 'Heyuan',
 4417: 'Yangjiang',
 4418: 'Qingyuan',
 4419: 'Dongguan',
 4420: 'Zhongshan',
 4452: 'Jieyang',
 4501: 'Nanning',
 4502: 'Liuzhou',
 4503: 'Guilin',
 4504: 'Wuzhou',
 4505: 'Beihai',
 4506: 'Fangchenggang',
 4507: 'Qinzhou',
 4508: 'Guigang',
 4509: 'Yulin4',
 4510: 'Baise',
 4511: 'Hezhou',
 4512: 'Hechi',
 4513: 'Laibin',
 4514: 'Chongzuo',
 4601: 'Haikou',
 4602: 'Sanya',
 5001: 'Chongqing',
 5101: 'Chengdu',
 5103: 'Zigong',
 5104: 'Panzhihua',
 5105: 'Luzhou',
 5106: 'Deyang',
 5107: 'Mianyang',
 5108: 'Guangyuan',
 5109: 'Suining',
 5110: 'Neijiang',
 5111: 'Leshan',
 5113: 'Nanchong',
 5114: 'Meishan',
 5115: 'Yibin',
 5116: 'GuangAn',
 5117: 'Dazhou',
 5118: 'Yaan',
 5119: 'Bazhong',
 5120: 'Ziyang',
 5201: 'Guiyang',
 5203: 'Zunyi',
 5301: 'Kunming',
 5303: 'Qujing',
 5304: 'Yuxi',
 5305: 'Baoshan',
 5306: 'Zhaotong',
 5307: 'Lijiang',
 5308: 'Simao',
 5309: 'Lincang',
 6101: 'XiAn',
 6102: 'Tongchuan',
 6103: 'Baoji',
 6104: 'Xianyang',
 6105: 'Weinan',
 6106: 'YanAn',
 6107: 'Hanzhong',
 6108: 'Yulin2',
 6109: 'Ankang',
 6110: 'Shangluo',
 6201: 'Lanzhou',
 6202: 'Jiayuguan',
 6203: 'Jinchang',
 6204: 'Baiyin',
 6205: 'Tianshui',
 6206: 'Wuwei',
 6207: 'Zhangye',
 6208: 'Pingliang',
 6209: 'Jiuquan',
 6210: 'Qingyang',
 6211: 'Dingxi',
 6212: 'Longnan',
 6301: 'Xining',
 6401: 'Yinchuan',
 6402: 'Shizuishan',
 6403: 'Wuzhong',
 6404: 'Guyuan',
 6405: 'Zhongwei',
 6501: 'Urumqi',
 6502: 'Karamay'}

In [81]:
df_cleaned = df_cleaned.rename(index = mapping, columns= mapping)

In [82]:
df_cleaned.to_csv('china_network.csv')